Clean up database provider list of MC
materialscloud-org/tools-optimade-client pull request #116
Opened 2022-06-29 13:19 UTC by unkcpz

According to Nicola, he wants to have MC3D and MC2D on the main list.
I also change the name of subgroup 'General' -> 'Main Projects' and 'Projects' -> 'Contribution Projects'.
Any idea what is the more proper name for the list? pinning @giovannipizzi, @csadorf @eimrek @CasperWA for comment about the name.

2022-06-29 14:17 UTC, unkcpz commented
This change also needs to make for QeApp which is inconvenient as described by @csadorf  https://github.com/aiidalab/aiidalab-qe/issues/155#issuecomment-972934387

I think the question is in which repository we put the static file (txt, or JSON) as the default group list. In my opinion, in order that the list to be used by 'downstream' package, it need to be put in `voila-optimade-client` and used by `tools-optimade-client` here and by `aiidalab-base-widget` for QeApp.
In this case, may be it is a quick implementation to just create a dict `DEFAULT_DATABASE_GROUPING` as const variable in `optimade_client` library contained and installed by `voila-optimade-client`.

What do you think? @CasperWA

2022-07-04 07:39 UTC, CasperWA requested changes
Seems fine to me.
I'm just removing two empty code cells and reverting an unnecessary change in the kernel's display name.

2022-07-04 07:39 UTC, CasperWA commented on OPTIMADE-Client.ipynb
> +   "source": []
```suggestion
```

2022-07-04 07:39 UTC, CasperWA commented on OPTIMADE-Client.ipynb
> +   "display_name": "Python 3 (ipykernel)",
```suggestion
   "display_name": "Python 3",
```

2022-07-04 08:08 UTC, eimrek commented
Hi @unkcpz, I think the names you proposed work well. But i would use "Contributed projects" instead of "Contribution projects".

Also, just to be aware, the names of the two main optimade databases will be changed to "mc3d" and "mc2d", after the aiida-2.0 migration: https://github.com/materialscloud-org/openstack-ansible/pull/154

2022-07-04 11:30 UTC, unkcpz commented on OPTIMADE-Client.ipynb
> +   "display_name": "Python 3 (ipykernel)",
changed.

2022-07-04 11:32 UTC, unkcpz commented
@CasperWA @eimrek 

thanks for the review! Updated upon your suggestion. 

>  just to be aware, the names of the two main optimade databases will be changed to "mc3d" and "mc2d", after the aiida-2.0 migration

Yes, I will keep it in mind after that we need also to rerun `mc_optimade_index` role.

2022-07-08 12:53 UTC, eimrek commented
Looks good! But could you push this to dev-dokku to demonstrate the changes and that it works as intended? (as i understand, that's what the dev machine is for, right?)

2022-07-08 13:01 UTC, unkcpz commented
@eimrek Thanks! Once merged, it will automatically be deployed to the dev server by the CI action. https://github.com/materialscloud-org/tools-optimade-client/blob/master/.github/workflows/cd_dev-dokku.yml

2022-07-08 13:03 UTC, merged

2022-07-08 13:15 UTC, unkcpz commented
Seems works fine https://optimadeclient.matcloud.xyz/